### ISSUE TITLE
Fix issues related to github pages

### ISSUE THREAD

**Issue by akuleshov7** [akuleshov7/diKTat#25]
Now it is failing due to a code style on chinese

**Comment by petertrr** [comment]
It actually fails because it tries to parse `{{` as some special tag, while in code style it is used as nested array literal, and one occurrence isn't properly closed:
``- `String[][] xs = {{"foo"}};`（`{{`多维数组之间不需要空格）``
Google suggest to use `{% raw %}` / `{% endraw %}` block in markdown to escape `{{` and `}}`.
